### ISSUE TITLE
Dúvidas para gerar danfe

### ISSUE THREAD

**Issue by AllisonErd** [danielbohnrs/danfe#1]
Primeiramente, obrigado @danielbohnrs por sua atenção e disponibilizar a função, agradeço de coração.
Cara, gostaria, se possível, uma ajudar sua para fazer funcionar. estou recebendo um NullPointerException nessa linha abaixo:

![image](https://user-images.githubusercontent.com/5253151/42940302-59319d10-8b2f-11e8-8050-1d58ccabe316.png)

Se puder me dá mais essa força, será de grande ajuda.
Obrigado e bom dia.

**Comment by danielbohnrs** [comment]
Bom dia
você está passando o xml de distribuição para dentro da função?
o segundo parâmetro ali indica em que nível estão os Itens da nota, então se não for o xml de distribuição, não vai encontrar os itens em /nfeProc/NFe/infNfe/det

para gerar a danfe de notas que ainda não foram enviadas, eu apenas adiciono a tag <nfeProc> no inicio e no final do xml que funciona

**Comment by AllisonErd** [comment]
Obrigado por responder @danielbohnrs 
Estou passando sim. Peguei o meu xml, converti ele em um objeto NotaProcessada usando a clase DFParser(), e verifiquei o xml em busca da tag 'det' e encontrei o seguinte 'det nItem="1"' e 'detPag'.

**Comment by danielbohnrs** [comment]
Tenta fazer como neste exemplo: carrega o xml de distribuição para uma string e aí passa pra dentro do construtor NFDanfeReport

String xmlNota ="<nfeProc...";

NFDanfeReport danfe = new NFDanfeReport(xmlNota);

byte[] logo = null;

JasperPrint jasper = danfe.createJasperPrintNFe(logo);

byte[] byteArray = JasperExportManager.exportReportToPdf(jasper);

**Comment by AllisonErd** [comment]
@danielbohnrs fiz como vc indicou e deu um erro diferente, segue:
`Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
	... 60 more
Caused by: java.lang.NoClassDefFoundError: net/sourceforge/barbecue/BarcodeException
	at net.sf.jasperreports.components.barbecue.BarbecueFillComponent.setBarcodeImage(BarbecueFillComponent.java:142)
	at net.sf.jasperreports.components.barbecue.BarbecueFillComponent.fill(BarbecueFillComponent.java:111)
	at net.sf.jasperreports.engine.fill.JRFillComponentElement.fill(JRFillComponentElement.java:198)
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.fillElements(JRFillElementContainer.java:1039)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:469)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:428)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillBandNoOverflow(JRVerticalFiller.java:448)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillPageHeader(JRVerticalFiller.java:409)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:258)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:110)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:615)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:432)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:162)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:689)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:670)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:992)
	at acom.gerenciadornfe.controle.nota.NFDanfeReport.createJasperPrintNFe(NFDanfeReport.java:57)
	at acom.gerenciadornfe.controle.nota.NotaControler.imprimirDanfe(NotaControler.java:1024)
	at acom.gerenciadornfe.controle.telas.FXMLNotaFiscal.cliqueBtnImprimirDanfe(FXMLNotaFiscal.java:684)
	... 70 more
Caused by: java.lang.ClassNotFoundException: net.sourceforge.barbecue.BarcodeException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 90 more`

Estou a procura do que seja. Se já tiver acontecido isso com vc, dá um toque.

**Comment by danielbohnrs** [comment]
Pela mensagem de erro está faltando a classe net.sourceforge.barbecue para gerar o código de barras.
Qual versão da lib do Jasper tu está usando no teu projeto?

**Comment by AllisonErd** [comment]
Estou usando o maven, está daqui: 
`<dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.6.0</version>
        </dependency>`

**Comment by danielbohnrs** [comment]
dentro deste projeto da danfe tem esta dependência aqui, que é a necessária para gerar o código de barras, ela está aí?
```

<dependency>
			<groupId>net.sourceforge.barbecue</groupId>
			<artifactId>barbecue</artifactId>
			<version>1.5-beta1</version>
		</dependency>
```

**Comment by danielbohnrs** [comment]
Eu uso o jasper 6.0.0 mas não deve ter influência, desde que tenha este componente de barcode

**Comment by AllisonErd** [comment]
Muito obrigado @danielbohnrs , era isso mesmo que faltava. Eu não cheguei a importar esse seu projeto todo, só peguei o que era relacionado ao DANFE, e não olhei o pom.xml. Muito obrigado, consegui gerar. Vou agora fazer outros testes como gerar nota com duplicata e outros. Qualquer coisa volto a pertubar vc aqui hehehe.

Obrigado de verdade! :)

**Comment by danielbohnrs** [comment]
;)
Qualquer coisa prende o grito!
